name: Terraform Deploy

on:
  push:
    branches:
      - master
    paths:
      - infra/**
      - app/web/**
      - app/lambda/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./infra

    env:
      TF_LOG: INFO
      TF_IN_AUTOMATION: true

      TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
      TF_VAR_dns_domain: ${{ secrets.DNS_DOMAIN }}
      TF_VAR_dns_subdomain: ${{ secrets.DNS_SUBDOMAIN }}
      TF_VAR_acm_cert_arn: ${{ secrets.AWS_CERT_ARN }}
      TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      TF_VAR_cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials from GitHub OIDC
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: gha-terraform-deploy
          unset-current-credentials: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.AWS_BACKEND_BUCKET }}" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="key=${{ secrets.AWS_BACKEND_BUCKET_KEY }}" \
            -backend-config="encrypt=true"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -no-color -out=tfplan

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan

      - name: Send email notification on success
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "✅ Notification: Chatbot App Updated Completed"
          to: ${{ secrets.EMAIL_USERNAME }}
          from: ${{ secrets.EMAIL_USERNAME }}
          html_body: |
            <h2>Chatbot App Updated Completed</h2>
            <p>Application infrastructures updated successfully.</p>
            <p>Branch: <b>${{ github.ref_name }}</b></p>
            <p>Workflow: <b>${{ github.workflow }}</b></p>
            <p>Commit: <b>${{ github.sha }}</b></p>
            <p><a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Workflow Run</a></p>

      - name: Send email notification on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "❌ Notification: Chatbot App Updated Failed"
          to: ${{ secrets.EMAIL_USERNAME }}
          from: ${{ secrets.EMAIL_USERNAME }}
          html_body: |
            <h2>Chatbot App Updated Failed</h2>
            <p>There was an error updating infrastructure.</p>
            <p>Branch: <b>${{ github.ref_name }}</b></p>
            <p>Workflow: <b>${{ github.workflow }}</b></p>
            <p>Commit: <b>${{ github.sha }}</b></p>
            <p><a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Workflow Run</a></p>
